### ISSUE TITLE
Can't build a search light with a mod for increasd light radius 

### ISSUE THREAD

**Issue by sebesPL** [Lamer87/Space_Engineers_DLC_unlocker#13]
Hello there i tried building search light as a way to spot enemies easier at night and also it looks cool that way but the max light radius
for the search light is 160m even tho for the AI to spot the target and aim it's 800m so to make it even more cool looking i installed a
mod to increase the light max radius i thought it worked correctly because at first the search lights i build before installing the mod
then adding mod i could customize the radius of light to be longer than 160m but only on the search lights that i already built
because when i added this mod i could no longer build the search light whenever i tried searching it was slightly darker then the other
blocks and when i wanted to add it to my toolbar is said that i need warfare 2 DLC to build it of course when i removed the mod for the increased serach light radius i could build it again so my question is there a possibility for this DLC unlocker to work with the mod
or am i stuck to building search lights then adding the mod and removing it again i forgot to mention that whenever i delete mod
all the search lights return to default settings also here are the mods that tried using with both having the same effect also even if unlocker won't work with mods Thank you for the unlocker and thank you for your help

https://steamcommunity.com/sharedfiles/filedetails/?id=2741701803
https://steamcommunity.com/sharedfiles/filedetails/?id=1197922657

**Comment by Lamer87** [comment]
The problem is the mod itself, the searchlight is blocked by the dlc through the mod.
I easily modified the mod to unlock it: [download](https://mega.nz/file/bAAjxIoT#v1rzdAKujwroctPMW9GyN4CiepmPZzlpcSoiGQU-hAw)

1- Unzip the folder
2- Place it in C:\Users\YOUR ACCOUNT NAME\AppData\Roaming\SpaceEngineers\Mods
3- Open the game, go to the mods list, refresh, use the one with "no dlc"

Note: if the original mod will be updated, this one will NOT be updated too, because it becomes a "local" mod (house icon in mods list).

**Comment by sebesPL** [comment]
Hi again Thank you for the reply your time and work the modified mods work great but for some reason the mod with spotlights radius didn't want to load to my main world and then got a pop up that siad the world may be corrupted so a little hearth attack but when i loaded the mod to a new world with only the spotlight radius it worked so i loaded my main world with your modified search light and it worked and luckily it wasn't corrupted although when i wanted to save and exit the game crashed and without thinking i closed the window with crash log  so i loaded save to see if the world did save before crashing and it did after loading my save checked to see if the mod worked correctly it did with the already built one and the one i built after the crash waited walked around got a bit further from my base to see if it works then i clicked save and exit but this time without a crash so it's all good the only thing i can't use modified spotlights on my main save but generally it works just not on my main save but that's fine i mainly waned search lights and if there will be time when i want spotlights to have longer radius i just use search light turning the AI off and idle movement the is option to control spotlight Couse it does have camera in the block witch can be used to aim 

Again Thank you for your time and help Great job :)
