### ISSUE TITLE
Issues getting this tool to work

### ISSUE THREAD

**Issue by Enxy999** [Lamer87/Space_Engineers_DLC_unlocker#14]
Hello! is this Tool still up to date? I've tried and tried to get it to work but to no avail. If you could help me that would be fantastic!

**Comment by Lamer87** [comment]
Yes, it works! you just have to put the right folder in the game folder, read the instructions carefully. nothing else!
And if you have a different version (like automatons beta) then it can't work, when I had time to download it the beta was already closed. So we have to wait for the official release.

**Comment by Lamer87** [comment]
Maybe you're confusing the folders, so I'll explain better...
Inside the zip you will find 2 folders, the one we are interested in is the "DLC Unlocker" folder inside which you will find another called "Content", this last one is the one you have to copy inside the game folder.
