### ISSUE TITLE
XML for Heavy Industry 

### ISSUE THREAD

**Issue by BellemareMederic** [Lamer87/Space_Engineers_DLC_unlocker#3]
Yeah ! nicework for all the DLC, just saying that new dlc is release today "Heavy Industry" do you know if you have time to patch it ?

**Comment by Tobesy** [comment]
Cant wait for this patch!

**Comment by AdrianOkay** [comment]
I updated it to Heavy industry and you can check it on my profile, since seems this person stopped playing space engineers i did it myself

**Comment by wrefgtzweve** [comment]
> I updated it to Heavy industry and you can check it on my profile, since seems this person stopped playing space engineers i did it myself

Couldn't you just put it unzipped on github? why zip it

**Comment by Lamer87** [comment]
i am really sorry but i am working about 12 hours a day (summer job), i will try to release a patch asap, i am currently downloading the game update from steam (1gb), but i need to go sleep so i think within 24/48 hours i will be able to release the update...

**Comment by Lamer87** [comment]
DONE!
small changes in almost all files with the update, so I have updated ALL files, and fixed the latest from heavy industry :)

**Comment by Lamer87** [comment]
added links of both your dlc unlockers on my readme ;)
