### ISSUE TITLE
World Failed To Save

### ISSUE THREAD

**Issue by DarthJustin08** [Lamer87/Space_Engineers_DLC_unlocker#34]
ever since I used the dlc unlocker my singleplayer worlds don't save, they say something like world failed to save check logs for more info, but it doesn't say much in the logs. I verified my steam files and it ended up working but only because when it verified it restored the original game files therefore the dlcs were locked again

**Comment by Lamer87** [comment]
When in a world there are problems like these, you have to start new world (with unlocker and all mods on) and I'm sure that this do not happen.
Btw, you have to try remove some mods to see if there is a problem with a mod and the unlocker together.
