### ISSUE TITLE
DLC blocks on Server?

### ISSUE THREAD

**Issue by jozsaVilmos** [Lamer87/Space_Engineers_DLC_unlocker#38]
Hi I can use the DLCs fine in singleplayer but not on a server when pasting a vehicle with dlc blocks. I can place the blocks fine. Is this intentional and DLCs will never work online?

**Comment by Lamer87** [comment]
I thought that with creamapi this problem no longer existed, but it still exists...
Unfortunately no, when you paste a blueprint into a server, the DLC blocks will not be present.
