### ISSUE TITLE
Armor skins not working

### ISSUE THREAD

**Issue by fiorematteo** [Lamer87/Space_Engineers_DLC_unlocker#41]
When using this I can't appy armor skins, is there any way to fix this?
I don't expect to unlock all armor skins but I'd like to be able to use the ones I do own.

**Comment by Lamer87** [comment]
Let me get this straight, do you own any DLC?
If so, it would be enough to delete the lines that contain the DLCs already owned in the "cream_api.ini" file, but if you don't feel like doing it, I can do it, just tell me which DLCs you already own, I'll create a cream_api.ini file just for you.

If you're referring to the base game skins instead, then you should be able to use them.

**Comment by fiorematteo** [comment]
I own a couple of the dlcs. If it's as easy as removing the right line in the .ini file I can manage on my own.
It could be useful to explain this in the readme.
Thanks

**Comment by Lamer87** [comment]
Perfect, just remove the dlc lines of dlc you own and everything should be back to normal.
I actually thought about it for the readme, now I'll add this situation, thanks for the support :)

**Comment by Fently** [comment]
From what I can see, armor skins do not work regardless of owned DLC. They always appear locked. Is this not the case for you?

**Comment by Lamer87** [comment]
they are locked only if you don't "really" have that dlc.
But, if you have a legit one you need to do something like this:
if you have frostbite dlc (legit), cut off the line of the frostbite dlc inside the file cream_api.ini and save it.
This way, creamapi do not touch that dlc and steam take care of it, the legit way.
