### ISSUE TITLE
DLC skins don't work - oldest issue - can't be fixed -

### ISSUE THREAD

**Issue by Sybuna** [Lamer87/Space_Engineers_DLC_unlocker#50]
It seems that not all paint skins in the color picker are working.
Some of them don't work, including Wasteland, which I would really like to use.
It might be that some of them are working because I bought the Deluxe Edition back then.
Could you make it work or at least get the color block skin from Wasteland to work?
<img width="474" alt="SE color skins" src="https://github.com/Lamer87/Space_Engineers_DLC_unlocker/assets/89865570/d354f65b-5a16-45c6-bde1-b8df1e4f2e89">

**Comment by Lamer87** [comment]
You can find this on the main page:

***
- 📜 ***Other Notes:***

  - This unlocker is meant to unlock DLC blocks, so you can use them without paying for DLC.
    - Armor Skins and Emotes cannot be unlocked (there is no way).
***

Even with the old method (.sbc files) we can't unlock skins.

**Comment by Lamer87** [comment]
Youre welcome and yes, it is really a shame.
