### ISSUE TITLE
Can't Download Workshop Scripts

### ISSUE THREAD

**Issue by nearlyNonexistent** [Lamer87/Space_Engineers_DLC_unlocker#52]
Crashes whenever I try, using either the 4.5 or the later version in the folder. Is this fixable, or am I going to have to download them all out of game? Is fine either way.

**Comment by Lamer87** [comment]
Sorry but what do you mean with "download"?

Like when you edit a programmable block to add the script (already subscribed)?

Or when you are you using the steam interface browser (ingame) to subrscibe scripts?
In this case, try alt-tabbing out of the game and use steam browser or your default browser to do it.

By the way, it's not something that I can fix.

If you are using Plugin Launcher maybe it's something related to it (dll injection messing with something), and not related to creamapi.

**Comment by Shiiki1** [comment]
Is it possible to download workshop mods after using the unlocker?
Thanks!

**Comment by Lamer87** [comment]
No problem, Steam Workshop mods does NOTHING to the unlocker.
AND, the unlocker does NOTHING to the mods, or the "download" (steam take care of it when you subscribe), or everything else.

**Comment by FlyinP** [comment]
Yes, when trying to browse any workshop items or scripts from the game the game crashes. Removing the DLC unlocker fixes this issue. Looking at the log I see this error:

>Unable to find an entry point named 'SteamAPI_ISteamUGC_CreateQueryAllUGCRequestPage' in DLL 'steam_api64'.

**Comment by Lamer87** [comment]
Are you using Plugin Launcher or JUST creamapi?

Anyway I have no time at the moment guys (summer job), you can try with the [new 5.3 creamapi](https://mega.nz/file/XQ4TUJra#l4nHgiaUa3yKWmiRvKd1FvGFC2VkSsMFt3eFqNAT-LY).
Do not use the tool because it does not recognize this new one, I'll make an update when I have time in september.
