### ISSUE TITLE
AppId need to be lowercase

### ISSUE THREAD

**Issue by Vidkol18** [Lamer87/Space_Engineers_DLC_unlocker#53]
In the config file ([cream_api.ini](https://github.com/Lamer87/Space_Engineers_DLC_unlocker/blob/main/cream_api.ini))
AppID = 244850

didn't work for me I had to make it all lowercase.
appid = 244850

**Comment by Lamer87** [comment]
Can you tell me if you are using only creamapi or also plugin launcher?
Btw I'll change it anyway.
Thanks.

**Comment by Lamer87** [comment]
Omg tested plugin launcher and it works now with the lower case and creamapi v5.3.
In the weekend I'll make an update of the tool, cause now only the latest creamapi is required.
Thank you very very much!
If only more people like you were willing to help...

**Comment by Vidkol18** [comment]
I was using just the creamapi.

Glad I was able to help 😄
