### ISSUE TITLE
Extreme sim speed drops on offline singleplayer game

### ISSUE THREAD

**Issue by Zemogiter** [Lamer87/Space_Engineers_DLC_unlocker#54]
After installing this script I'm experiencing severe drops in sim speed, down to 0.08
Started fine but when I started welding the warfare thrusters and solar panels on my jump ring the drops began.
Unlocker version 1.6.1
Log files:
[SpaceEngineers_20241107_203327682.log](https://github.com/user-attachments/files/17668708/SpaceEngineers_20241107_203327682.log) game log

[loader.log](https://github.com/user-attachments/files/17668719/loader.log)
[launcher.log](https://github.com/user-attachments/files/17668720/launcher.log)
PluginLoader logs (issue is present even without PluginLoader)

[Star System Vanilla+.zip](https://github.com/user-attachments/files/17668734/Star.System.Vanilla%2B.zip)
save file

**Comment by Lamer87** [comment]
Hi, I think it's a plugin/mod's fault, or some incompatibility between them.
My tool is only used to manage the installation and removal of creamapi, as well as to clean all the launcher plugin files as a bonus. Creamapi has nothing to do with the simulation performance, in fact, if you try to disable creamapi you will see that the same thing will happen.
You have to try to find which plugin is the culprit of this (disabling a few at a time), or try to understand if 2 plugins conflict with each other.
Unfortunately that's all I can tell you.
Let me know if the problem persists even with creamapi disabled.
PS: you can safely disable creamapi (R + R in the tool), the dlc blocks already created will not disappear, so load your game and try, but I'm sure that creamapi is not the culprit.

**Comment by Zemogiter** [comment]
I've tried creamapi removal, issue remained. Then no unlocker and vanilla game exe, same thing. Removed wrecks and floating objects in SEToolbox. Still the same issue.

**Comment by Lamer87** [comment]
if the issue remained even with vanilla exe, there is something wrong whit your actual run.
1- have you tried removing all the mods (if there are)?
  - if you solve, there is some mod causing the issue.
2- Try starting a new world, and see if this happen.
  - if you not solve, try recheck files via steam.

Quote: "I did not change the plugin list recently"
- Yes, but the game have got a really big update that broke a lot of mods and plugins, maybe there is something wrong now.
